# _config.yml

# Основная информация о сайте
title: "ALM Open Source Project"
description: "The goal of the project is to create an open source framework for automating calculations in the field of asset and liability management"
baseurl: "" # Оставьте пустым, если репозиторий называется alminance.github.io
url: "https://alminance.github.io" # Ваш URL
github_username: alminance
repository: "alminance/alminance" # Имя репозитория

# Настройки Jekyll
theme: minima # Можно использовать другую встроенную тему (minima - самая простая)
plugins:
  - jekyll-feed

# Настройки для сайта OSS проекта
header_pages: # Страницы, которые будут в навигации
  - about.md
  - blog.md    # New page
  - github.md  # New page

# Blog settings
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Ваши кастомные переменные для легкой смены оформления
custom:
  primary_color: "#2563eb"   # Основной синий цвет (для кнопок, ссылок)
  background_color: "#f8fafc" # Цвет фона
  text_color: "#1e293b"       # Цвет основного текста
  accent_color: "#f59e0b"     # Акцентный цвет (для предупреждений, highlights)